insert into admin (email,matkhau,ten,sodienthoai) values ('thuannef','123','Phạm Trần Thanh Thuận','0965349315')
insert into admin (email,matkhau,ten,sodienthoai) values ('thien','123','Phạm Trần Thanh Thuận','0965349315')
insert into admin (email,matkhau,ten,sodienthoai) values ('hoang','123','Phạm Lê Nguyễn Hoàng','0356783513')
insert into admin (email,matkhau,ten,sodienthoai) values ('hoang','1234','Phạm Lê Nguyễn Hoàng','0356783513')
insert into admin (email,matkhau,ten,sodienthoai) values ('hoang','1235','Phạm Lê Nguyễn Hoàng','0356783513')

insert into nhomsanpham values ('Bửng xe','Bửng xe')
insert into nhomsanpham values ('Dè xe','Dè xe')
insert into nhomsanpham values ('Đầu xe','Đầu xe')
insert into nhomsanpham values ('Đuôi xe','Đuôi xe')
insert into nhomsanpham values ('Mặt nạ xe','Mặt nạ xe')
insert into loaisanpham values ('Đèn xe','Đèn xe')
